version: '3.8'

services:
  auth-service:
    build: .
    container_name: auth-service
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=18.232.41.255  
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD} 
      - SESSION_TTL=3600
      - USER_PROFILE_SERVICE_URL=http://34.193.149.183:8000  
      - AWS_REGION=us-east-1 
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3


networks:
  default:
    driver: bridge
    name: lavanet-net